[book]
authors = ["Klaus Ostermann"]
language = "en"
multilingual = false
src = "out"
title = "Programming Languages I"
description = "Lecture notes for the Programming Languages I lecture at the University of Tübingen"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/ps-tuebingen-courses/pl1-lecture-notes"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/ps-tuebingen-courses/pl1-lecture-notes/blob/master/{path}"
additional-js =["questionnaire.js"]
