name: Publish GH Page
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Download Latest Version Questionnaire Module
      run: sh download_questionnaire_module.sh

    - name: Install mdbook
      run: |
        mkdir mdbook
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.15/mdbook-v0.4.15-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH

    - name: Run mdoc
      run: ./generateMarkdown.sh

    - name: Create Downloadable Racket Files.
      run: ./create_rkt_files.sh

    - name: Copy Racket files from src to out
      run: ./copy_rkt_files.sh

    - name: Create Downloadable Scala Files.
      run: ./create_scala_files.sh

    - name: Copy Scala files from src to out
      run: ./copy_scala_files.sh


    - name: Create mdBook page
      run: mdbook build

    - name: Dirty fix edit-URLs
      run: ./dirty-fix-edit-url.sh

    - uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
          branch: gh-pages
          folder: book
